### ISSUE TITLE
Add README file to describe build steps

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift-b2d-iso#1]

**Comment by hferentschik** [comment]
The README should contain

* Description what the repo is about
* Some history (where it derives from, link to boot2docker)
* How to build the ISO
* How to test the ISO (once smoke tests are added)
* Link to CI (once available)

**Comment by LalatenduMohanty** [comment]
This is resolved as part of commit https://github.com/minishift/minishift-b2d-iso/commit/95ea4814a01be9340e80f239825ba18e3c783ab9.
