### ISSUE TITLE
What should be the first release version of this repository?

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift-b2d-iso#11]
I think we should we  docker version (similar to upstream boot2docker) + `a minor version` e.g. 1 , 2, 3 etc as the release version e.g.  1.12.3-1

**Comment by hferentschik** [comment]
I'd rather do semantic versioning and start somewhere at 1.0.0. The VM is not necessarily aligned to the Docker version, right?

That said, we should get the ISO release version into the VM, so that it can be inspected as well.

**Comment by LalatenduMohanty** [comment]
This is resolved as part of commit https://github.com/minishift/minishift-b2d-iso/commit/95ea4814a01be9340e80f239825ba18e3c783ab9.

**Comment by LalatenduMohanty** [comment]
@hferentschik I have opened a new issue https://github.com/minishift/minishift-b2d-iso/issues/13 to track the release version stuff.
