### ISSUE TITLE
Docker config should be persistent during restart

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift-b2d-iso#25]
Currently b2d images doesn't have docker options persistent and restart will overwrite whatever configuration we change during a session. We need a persistent docker config to expose internal openshift registry and for proxy stuff.

**Comment by hferentschik** [comment]
Is this still an issue?

**Comment by praveenkumar** [comment]
@hferentschik now it not a issue any more since internal docker registry have fix IP.

**Comment by hferentschik** [comment]
Thanks.
