### ISSUE TITLE
We need to fix code related to make_iso.sh as Boot2Docker has changed its path

### ISSUE THREAD

**Issue by LalatenduMohanty** [minishift/minishift-b2d-iso#26]
Upstream boot2docker has changed the path of make_iso.sh [1] , hence our builds will fail once we move to any docker version later `v1.12.4-rc1`. 

We have two ways to fix this. Either [2] [3] can be fixed or we can put the make_iso.sh in our repository. We can also also fetch it from the upstream repository through the Makefile automatically every time we do a build.

[1] https://github.com/boot2docker/boot2docker/commit/2d5e77def87a9b9daa156c44bc17d8af183a4744
[2] https://github.com/minishift/minishift-b2d-iso/blob/master/iso/Dockerfile#L52
[3] https://github.com/minishift/minishift-b2d-iso/blob/master/iso/Dockerfile#L25

**Comment by brgnepal** [comment]
> we can put the make_iso.sh in our repository.

Does it mean we copy it from b2d upstream repo and put in our repository? If yes, then isn't it creates a maintenance overhead?

> We can also also fetch it from the upstream repository through the Makefile automatically every time we do a build.

This seems to one of possible way where maintenance overhead is handled automatically.

> Either [2] [3] can be fixed

+1 for this.

**Comment by LalatenduMohanty** [comment]
Resolved by https://github.com/minishift/minishift-b2d-iso/pull/50
