### ISSUE TITLE
Add `cifs-utils` to allow mounting cifs fileshares

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift-b2d-iso#29]
To allow mounting of fileshares, as described in minishift/minishift#316, we need to add `cifs-utils` to the image.

**Comment by gbraad** [comment]
Unlike minishift/minishift-centos-iso#99, `mount -t cifs` gives no output if this is not supported. This means we can not test for support, instead I check for `/sbin/mount.cifs` and the output.

**Comment by hferentschik** [comment]
> Unlike minishift/minishift-centos-iso#99, mount -t cifs gives no output if this is not supported. This means we can not test for support, instead I check for /sbin/mount.cifs and the output.

Fair enough. Is there otherwise no sort of package management command one could use? I guess not?

**Comment by gbraad** [comment]
> package management command

not sure if tce-load registered the package as it was unsquashed into the root filesystem. Likely it did, ... will check.

**Comment by gbraad** [comment]
The actual problem is dependency resolving. Earlier packaged versions of `cifs-utils` relied on a package called `samba3-libs` (and more). In later releases this was renamed to `samba-libs`. Because we prepare the image, we can not rely on the dependency resolution process. We have to do this manually.  I want to make sure the binary can actually run. For the CentOS image we do not have this problem, as the actually run an install process from during the livecd creator.
