### ISSUE TITLE
Does minikube directory have any use?

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift-b2d-iso#3]
After spiting from minishift/deploy we have `minikube` directory, I don't see any use case for it and I think it's fine to remove it. WDYT?

**Comment by hferentschik** [comment]
+1 for removing it. In fact why did you even include it in the first place. Why not doing the extraction from the _iso_ directory? I recommend we do this again w/o the _minikube_ directory.

**Comment by praveenkumar** [comment]
@hferentschik If I try split with /deploy/iso then every file will comes on top directory instead `iso` folder which we want so then we have to create that top level directory and need `git mv` which again need a commit message on whatever history we have. If we delete `minikube` that also need a single commit so I chose later one. Let me know if you think earlier is better.

**Comment by hferentschik** [comment]
> If I try split with /deploy/iso then every file will comes on top directory instead iso folder

this is what we want in the end, no?

> so then we have to create that top level directory and need git mv which again need a commit message on whatever history we have.

I am not following. TBH, I am not sure why one should not be able to just filter the iso directory. I am missing some context here.

> If we delete minikube that also need a single commit so I chose later one

Whatever works for you.

**Comment by LalatenduMohanty** [comment]
@praveenkumar If removing the directory through a single commit is the only way of doing it, lets do it.

**Comment by hferentschik** [comment]
> if removing the directory through a single commit is the only way of doing it, lets do it.

for the record, it is not the only way

**Comment by praveenkumar** [comment]
> for the record, it is not the only way

I agree but can we just go with this as cleanup commit and then different patch?

**Comment by LalatenduMohanty** [comment]
With `git filter-branch --prune-empty --subdirectory-filter deploy/iso master` we can only get the files in `iso` directory i.e. the root of the repository will have below files. 

Does it look fine to you guys?

```
$ tree ./
./
├── addon-manager.yaml
├── bootlocal.sh
├── build.sh
├── conntrack.sh
├── Dockerfile
├── Dockerfile.conntrack
├── Dockerfile.ethtool
├── Dockerfile.socat
└── README.md

```

**Comment by LalatenduMohanty** [comment]
I am also trying to see how we can get only the `iso` directory and files in it.  Let me know what do you guys think would be the right approach .Personally I feel https://github.com/minishift/minishift-b2d-iso/issues/3#issuecomment-270322104 should be fine for us to begin along with license , makefile.

**Comment by praveenkumar** [comment]
That's what I said instead of spending hell amount of time just do a cleanup commit and go with it. We already have issues and PR in place.

**Comment by LalatenduMohanty** [comment]
@praveenkumar We will fix it today without spending more time on it. Here are my suggestions

1.  We can remove the minikube directory and its history from this repository by running `git filter-branch --tree-filter 'rm -rf minikube' HEAD` . Then I can add makefile and license and I have to do a git force push.

Or

2. We can delete the repository and recreate it using `git filter-branch --prune-empty --subdirectory-filter deploy/iso master` . Then I can add Makefile and License and push it to github.  As I mentioned in https://github.com/minishift/minishift-b2d-iso/issues/3#issuecomment-270322104

I kind of like the 2nd option. However I am fine with the 1st option too.

**Comment by hferentschik** [comment]
Either works for me.

**Comment by LalatenduMohanty** [comment]
Cool, I am going with option one.

**Comment by LalatenduMohanty** [comment]
This is resolved as part of commit https://github.com/minishift/minishift-b2d-iso/commit/95ea4814a01be9340e80f239825ba18e3c783ab9.
