### ISSUE TITLE
Removing workaround to make avocado work in CentOS CI

### ISSUE THREAD

**Issue by gbraad** [minishift/minishift-b2d-iso#31]
If Avocado released a new version of their packages, we are able to remove the workaround to install [`python-setuptools`](https://github.com/minishift/minishift-b2d-iso/blob/master/centos_ci.sh#L28) from the centos_ci setup script.

Reference: avocado-framework/avocado#1798

**Comment by gbraad** [comment]
Scheduled to be released on the 6th (March)

**Comment by LalatenduMohanty** [comment]
Resolved by #66
