### ISSUE TITLE
gh-release usage is OS specific 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift-b2d-iso#33]
Current release target only works on Linux. Either get gh-release installed independent of the OS (go get!?) or make it a prerequisite to install it. As it stands now it won't work.

**Comment by LalatenduMohanty** [comment]
I will suggest we add support for OS X [1] and then document in the release documents that `make release` is only supported on OS X or GNU/Linux

[1] https://github.com/progrium/gh-release/blob/master/Makefile#L20

**Comment by nanomad** [comment]
Please also note that building the image itself on windows via Docker requires the usage of WSL due to windows line terminators screwing up wget in the Dockerfile

**Comment by brgnepal** [comment]
> I will suggest we add support for OS X [1] and then document in the release documents that make release is only supported on OS X or GNU/Linux

:+1:

**Comment by brgnepal** [comment]
@hferentschik WDYT about @LalatenduMohanty  comment here https://github.com/minishift/minishift-b2d-iso/issues/33#issuecomment-286070859 ?

**Comment by hferentschik** [comment]
I am not quite clear what 

> I will suggest we add support for OS X [1] and then document in the release documents that make release is only supported on OS X or GNU/Linux

entails.

I would be happy to just align with what we have in the main Makefile:

    go get -u github.com/progrium/gh-release/...

Only drawback is that it is not locked on a version, but I prefer that (in the case of gh-release) over jumping through the hoops of doing OS specific things in the Makefile.

**Comment by hferentschik** [comment]
See also https://github.com/minishift/minishift/blob/master/Makefile#L93

**Comment by brgnepal** [comment]
Resolved via https://github.com/minishift/minishift-b2d-iso/pull/53
