### ISSUE TITLE
Update docker version to sync with our CentOS Docker version

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift-b2d-iso#49]
Currently we are using 1.12.3 docker version and even our minishift-centos iso have `1.12.6` . It good have both sync.

**Comment by brgnepal** [comment]
> It good have both sync.

+1

**Comment by hferentschik** [comment]
We should take this into the next sprint.

**Comment by hferentschik** [comment]
Also addresses issue #26

**Comment by LalatenduMohanty** [comment]
Resolved by #50
