### ISSUE TITLE
Add minishift smoke tests 

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift-b2d-iso#5]
Similar to _minishift-centos-iso_, there should be smoke tests against minishift (preferably always  the latest release).

**Comment by LalatenduMohanty** [comment]
Moving this issue to v1.0.1 milestone as we need to release 1.0.0 for https://github.com/MiniShift/minishift/issues/134

**Comment by hferentschik** [comment]
Merged via pull request #18
