### ISSUE TITLE
Update test to force delete minishift instance

### ISSUE THREAD

**Issue by brgnepal** [minishift/minishift-b2d-iso#69]
With latest 1.6.0, we have added confirmation on delete operation. Update test accordingly.

**Comment by anjannath** [comment]
@budhrg so just replacing `minishift delete` with `minishift delete --force` should be fine.. right?

**Comment by brgnepal** [comment]
Yes @anjannath

**Comment by brgnepal** [comment]
Resolved via https://github.com/minishift/minishift-b2d-iso/pull/71
