### ISSUE TITLE
Add release target to Makefile

### ISSUE THREAD

**Issue by hferentschik** [minishift/minishift-b2d-iso#7]

**Comment by LalatenduMohanty** [comment]
The repository currently does not have a Makefile. Should we use this issue to add the Makefile?

**Comment by hferentschik** [comment]
Well, I would have expected that the initial import will take care of this. But yes, either as part of this issue or as part of the issue creating a unit test. I would also suggest to get rid of _build.sh_ and basically puts its content into the build target in the _Makefile_.

**Comment by LalatenduMohanty** [comment]
#15 Fixes this issue.
