### ISSUE TITLE
Cannot find make_iso.sh

### ISSUE THREAD

**Issue by rikbon** [minishift/minishift-b2d-iso#81]
Hi all, I'm trying to create the iso from scratch with some images i need but I'm facing a problem.

When parsing the Dockerfile, I get the following error

Step 4/17 : RUN sed -i '/^b2dVersion/,/^EOOS/d' /tmp/make_iso.sh
 ---> Running in 08136a0424be

sed: can't read /tmp/make_iso.sh: No such file or directory
The command '/bin/sh -c sed -i '/^b2dVersion/,/^EOOS/d' /tmp/make_iso.sh' returned a non-zero code: 2
make: *** [iso] Errore 2

Anybody has a clue?

**Comment by brgnepal** [comment]
@rikbon Which version of docker you are using? We have pinned to `1.13.1`.

**Comment by rikbon** [comment]
Hi, I'm using docker 1.13.1 as well on my machine and trying to install thw same version in the iso

**Comment by gbraad** [comment]
This sounds like an old issue... Can you show the exact steps executed? From git clone and onwards?

**Comment by rikbon** [comment]
I found out what the problem was...
I modified the Dockerfile to add origin and this mod brought havoc...

At this point I have  question, is it possibile to have openshift/origin directly in the iso, as the machine I have to install all this has no internet connection? I tried creating a local registry, but it didn't work.

**Comment by gbraad** [comment]
It is possible, but it would be kind of pointless if you want to create an instantly running OpenShift instance., as the deployment does not happen from the container itself, but from the `oc` client.

You should look into `minishift`'s image caching option, as this solves the problem of exporting and importing the image on start.

**Comment by gbraad** [comment]
https://docs.openshift.org/latest/minishift/using/image-caching.html
