### ISSUE TITLE
Create bind mount for `/var/lib/origin` to persistent volume.

### ISSUE THREAD

**Issue by praveenkumar** [minishift/minishift-b2d-iso#82]
With 3.10.x, the default directory for a remote docker daemon is `/var/lib/origin` which we can't change so this should be bind mounted properly.

**Comment by gbraad** [comment]
who decides it is /var/lib/minishift?

**Comment by gbraad** [comment]
ah, typo... this should have been `/var/lib/origin`

On Tue, Apr 24, 2018 at 2:01 PM, Gerard Braad <me@gbraad.nl> wrote:
> who decides it is /var/lib/minishift?



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by praveenkumar** [comment]
@gbraad right, I updated the description.

**Comment by LalatenduMohanty** [comment]
Resolved via #83
